groups:
- name: Container
  rules:

# =================================================================== REPORT ====================================================================

  - alert: Container Status report-service-dhy-production
    expr: container_state_status{status="exited",name=~"report-service-dhy-production",instance='192.168.55.195:19094'} == 1
    for: 1s
    labels:
      severity: khẩn cấp
      category: container-status
      container_name: report-service-dhy-production
      app_type: Đại Học Y
    annotations:
      summary: Container exited
      description: |

       CONTAINER NAME:-  {{ $labels.name }}

       CONTAINER BỊ TẮT 

  - alert: Container Memory report-service-dhy-production
    expr: (container_memory_working_set_bytes{job='dhy', name='report-service-dhy-production'}) / (container_spec_memory_limit_bytes{job="dhy", name='report-service-dhy-production', instance='192.168.55.195:19093'}) * 100 > 90
    for: 10s
    labels:
      severity: khẩn cấp
      app_type: Đại Học Y
      category: container-memory    
      container_name: report-service-dhy-production
    annotations:
      summary: "RAM container quá 90%"
      description: |
      
        CONTAINER NAME: 
        
        **report-service-dhy-production**

        Thông tin cụ thể: 

          RAM USED: {{ printf "%.2f" $value}}% / 100%

  - alert: Container CPU report-service-dhy-production
    expr: (sum(rate(container_cpu_usage_seconds_total{name!="",job='dhy',name='report-service-dhy-production',instance='192.168.55.195:19093' }[1m])) BY (instance, name) * 100) > 500
    for: 10s
    labels:
      severity: khẩn cấp
      app_type: Đại Học Y
      category: container-cpu    
      container_name: report-service-dhy-production
    annotations:
      summary: "CPU container quá 95%"
      description: |
      
        CONTAINER NAME: {{ $labels.name }}

        Thông tin cụ thể: 

          CPU USED : {{ printf "%.2f" $value}}%

  - alert: Container Status report-service-dhy-production-2415
    expr: container_state_status{status="exited",name=~"report-service-dhy-production-2415",instance='192.168.55.195:19094'} == 1
    for: 1s
    labels:
      severity: khẩn cấp
      category: container-status
      container_name: report-service-dhy-production-2415
      app_type: Đại Học Y
    annotations:
      summary: Container exited
      description: |

       CONTAINER NAME:-  {{ $labels.name }}

       CONTAINER BỊ TẮT 

  - alert: Container Memory report-service-dhy-production-2415
    expr: (container_memory_working_set_bytes{job='dhy', name='report-service-dhy-production-2415'}) / (container_spec_memory_limit_bytes{job="dhy", name='report-service-dhy-production-2415', instance='192.168.55.195:19093'}) * 100 > 90
    for: 10s
    labels:
      severity: khẩn cấp
      app_type: Đại Học Y
      category: container-memory    
      container_name: report-service-dhy-production-2415
    annotations:
      summary: "RAM container quá 90%"
      description: |
      
        CONTAINER NAME: 
        
        **report-service-dhy-production-2415**

        Thông tin cụ thể: 

          RAM USED: {{ printf "%.2f" $value}}% / 100%

  - alert: Container CPU report-service-dhy-production-2415
    expr: (sum(rate(container_cpu_usage_seconds_total{name!="",job='dhy',name='report-service-dhy-production-2415',instance='192.168.55.195:19093' }[1m])) BY (instance, name) * 100) > 500
    for: 10s
    labels:
      severity: khẩn cấp
      app_type: Đại Học Y
      category: container-cpu    
      container_name: report-service-dhy-production-2415
    annotations:
      summary: "CPU container quá 95%"
      description: |
      
        CONTAINER NAME: {{ $labels.name }}

        Thông tin cụ thể: 

          CPU USED : {{ printf "%.2f" $value}}%
  
# =================================================================== SIGNER ====================================================================

  - alert: Container Status signer-connector-dhy-production
    expr: container_state_status{status="exited",name=~"signer-connector-dhy-production",instance='192.168.55.195:19094'} == 1
    for: 1s
    labels:
      severity: khẩn cấp
      category: container-status
      container_name: signer-connector-dhy-production
      app_type: Đại Học Y
    annotations:
      summary: Container exited
      description: |

       CONTAINER NAME:-  {{ $labels.name }}

       CONTAINER BỊ TẮT 

  - alert: Container Memory signer-connector-dhy-production
    expr: (container_memory_working_set_bytes{job='dhy', name='signer-connector-dhy-production'}) / (container_spec_memory_limit_bytes{job="dhy", name='signer-connector-dhy-production', instance='192.168.55.195:19093'}) * 100 > 90
    for: 10s
    labels:
      severity: khẩn cấp
      app_type: Đại Học Y
      category: container-memory    
      container_name: signer-connector-dhy-production
    annotations:
      summary: "RAM container quá 90%"
      description: |
      
        CONTAINER NAME: 
        
        **signer-connector-dhy-production**

        Thông tin cụ thể: 

          RAM USED: {{ printf "%.2f" $value}}% / 100%

  - alert: Container CPU signer-connector-dhy-production
    expr: (sum(rate(container_cpu_usage_seconds_total{name!="",job='dhy',name='signer-connector-dhy-production',instance='192.168.55.195:19093' }[1m])) BY (instance, name) * 100) > 500
    for: 10s
    labels:
      severity: khẩn cấp
      app_type: Đại Học Y
      category: container-cpu    
      container_name: signer-connector-dhy-production
    annotations:
      summary: "CPU container quá 95%"
      description: |
      
        CONTAINER NAME: {{ $labels.name }}

        Thông tin cụ thể: 

          CPU USED : {{ printf "%.2f" $value}}%

# =================================================================== PDF ====================================================================

  - alert: Container Status pdf-generator-dhy-production
    expr: container_state_status{status="exited",name=~"pdf-generator-dhy-production",instance='192.168.55.195:19094'} == 1
    for: 1s
    labels:
      severity: khẩn cấp
      category: container-status
      container_name: pdf-generator-dhy-production
      app_type: Đại Học Y
    annotations:
      summary: Container exited
      description: |

       CONTAINER NAME:-  {{ $labels.name }}

       CONTAINER BỊ TẮT 

  - alert: Container Memory pdf-generator-dhy-production
    expr: (container_memory_working_set_bytes{job='dhy'pdf-generator-dhy-production'}) / (container_spec_memory_limit_bytes{job="dhy", name='pdf-generator-dhy-production', instance='192.168.55.195:19093'}) * 100 > 90
    for: 10s
    labels:
      severity: khẩn cấp
      app_type: Đại Học Y
      category: container-memory    
      container_name: pdf-generator-dhy-production
    annotations:
      summary: "RAM container quá 90%"
      description: |
      
        CONTAINER NAME: 
        
        **pdf-generator-dhy-production**

        Thông tin cụ thể: 

          RAM USED: {{ printf "%.2f" $value}}% / 100%

  - alert: Container CPU pdf-generator-dhy-production
    expr: (sum(rate(container_cpu_usage_seconds_total{name!="",job='dhy',name='pdf-generator-dhy-production',instance='192.168.55.195:19093' }[1m])) BY (instance, name) * 100) > 500
    for: 10s
    labels:
      severity: khẩn cấp
      app_type: Đại Học Y
      category: container-cpu    
      container_name: pdf-generator-dhy-production
    annotations:
      summary: "CPU container quá 95%"
      description: |
      
        CONTAINER NAME: {{ $labels.name }}

        Thông tin cụ thể: 

          CPU USED : {{ printf "%.2f" $value}}%


# =================================================================== PDF ====================================================================