groups:
- name: Container

  rules:
  - alert: Container Status ivirse-django-hdsd-label-production
    expr: container_state_status{status="exited",name=~"ivirse-django-hdsd-label-production"} == 1
    for: 1s
    labels:
      severity: khẩn cấp
      category: container-status
      container_name: ivirse-django-hdsd-label-production
      app_type: IVIRSE
    annotations:
      summary: Container exited
      description: |

       CONTAINER NAME:-  {{ $labels.name }}

       CONTAINER BỊ TẮT 

  - alert: Container Status ivirse-rasa-instructions-bot-production
    expr: container_state_status{status="exited",name=~"ivirse-rasa-instructions-bot-production"} == 1
    for: 1s
    labels:
      severity: khẩn cấp
      category: container-status
      container_name: ivirse-rasa-instructions-bot-production
      app_type: IVIRSE
    annotations:
      summary: Container exited
      description: |

       CONTAINER NAME:-  {{ $labels.name }}

       CONTAINER BỊ TẮT 


################################################  
################## RAM #########################  
################################################  

  - alert: Container Memory ivirse-rasa-instructions-bot-production
    expr: sum(container_memory_working_set_bytes{job='ivirse', name='ivirse-django-hdsd-label-production'}) / sum(container_spec_memory_limit_bytes{job="ivirse", id="/", instance="103.9.211.87:19094"}) * 100 > 90
    for: 10s
    labels:
      severity: khẩn cấp
      app_type: IVIRSE
      category: container-memory    
      container_name: ivirse-rasa-instructions-bot-production
    annotations:
      summary: "RAM container quá 90%"
      description: |
      
        CONTAINER NAME:
        
        **ivirse-rasa-instructions-bot-production**

        Thông tin cụ thể: 

          RAM USED: {{ printf "%.2f" $value}}% / 100%


  - alert: Container Memory ivirse-django-hdsd-label-production
    expr: sum(container_memory_working_set_bytes{job='ivirse', name='ivirse-django-hdsd-label-production'}) / sum(container_spec_memory_limit_bytes{job="ivirse", id="/", instance="103.9.211.87:19094"}) * 100 > 90
    for: 10s
    labels:
      severity: khẩn cấp
      app_type: IVIRSE
      category: container-memory    
      container_name: ivirse-django-hdsd-label-production
    annotations:
      summary: "RAM container quá 90%"
      description: |
      
        CONTAINER NAME:  
        
        **ivirse-django-hdsd-label-production**

        Thông tin cụ thể: 

          RAM USED: {{ printf "%.2f" $value}}% / 100%



################################################  
################## CPU #########################  
################################################  

  - alert: Container CPU ivirse-rasa-instructions-bot-production
    expr: (sum(rate(container_cpu_usage_seconds_total{name!="",job='ivirse',name='ivirse-rasa-instructions-bot-production',instance='103.9.211.87:19094'}[1m])) BY (instance, name) * 100) > 95
    for: 10s
    labels:
      severity: khẩn cấp
      app_type: Server Test
      category: container-cpu    
      container_name: ivirse-rasa-instructions-bot-production
    annotations:
      summary: "CPU container quá 95%"
      description: |
      
        CONTAINER NAME: {{ $labels.name }}

        Thông tin cụ thể: 

          CPU USED : {{ printf "%.2f" $value}}%

  
  - alert: Container CPU ivirse-django-hdsd-label-production
    expr: (sum(rate(container_cpu_usage_seconds_total{name!="",job='ivirse',name='project-react-js-wallet-ivirse-isofh-production',instance='103.9.211.87:19094'}[1m])) BY (instance, name) * 100) > 95
    for: 10s
    labels:
      severity: khẩn cấp
      app_type: Server Test
      category: container-cpu    
      container_name: ivirse-django-hdsd-label-production
    annotations:
      summary: "CPU container quá 95%"
      description: |
      
        CONTAINER NAME: {{ $labels.name }}

        Thông tin cụ thể: 

          CPU USED : {{ printf "%.2f" $value}}%