groups:
- name: Container


  rules:
  - alert: Container Status mongo
    expr: container_state_status{status="exited",name=~"mongo"} == 1
    for: 1s
    labels:
      severity: khẩn cấp
      category: container-status
      container_name: mongo
      app_type: IVIRSE
    annotations:
      summary: Container exited
      description: |

       CONTAINER NAME:-  {{ $labels.name }}

       CONTAINER BỊ TẮT 

  
################################################  
################## RAM #########################  
################################################  

  - alert: Container Memory mongo
    expr: sum(container_memory_working_set_bytes{job='ivirse', name='mongo'}) / sum(container_spec_memory_limit_bytes{job="ivirse", id="/", instance="103.9.211.87:19094"}) * 100 > 90
    for: 10s
    labels:
      severity: khẩn cấp
      app_type: IVIRSE
      category: container-memory    
      container_name: mongo
    annotations:
      summary: "RAM container quá 90%"
      description: |
      
        CONTAINER NAME:
        
        **mongo**

        Thông tin cụ thể: 

          RAM USED: {{ printf "%.2f" $value}}% / 100%


################################################  
################## CPU #########################  
################################################  

  - alert: Container CPU mongo
    expr: (sum(rate(container_cpu_usage_seconds_total{name!="",job='ivirse',name='mongo',instance='103.9.211.87:19094'}[1m])) BY (instance, name) * 100) > 95
    for: 10s
    labels:
      severity: khẩn cấp
      app_type: Server Test
      category: container-cpu    
      container_name: mongo
    annotations:
      summary: "CPU container quá 95%"
      description: |
      
        CONTAINER NAME: {{ $labels.name }}

        Thông tin cụ thể: 

          CPU USED : {{ printf "%.2f" $value}}%